---

- name: Delete parameter
  uri:
    force_basic_auth: yes
    user: "{{ sat_api_user }}"
    password: "{{ sat_api_password }}"
    method: DELETE
    url: "{{ sat_url }}/api/v2/smart_class_parameters/{{ param_id }}/override_values/{{ param_override_id }}"
    validate_certs: "{{ validate_certs }}"
  register: delete_sc_param_override
  changed_when: " 'status' in delete_sc_param_override and delete_sc_param_override.status == 200 "

- debug:
    var: delete_sc_param_override
    verbosity: 1
